<?php

declare(strict_types=1);

namespace PackageFactory\NodeTypeObjects\Domain;

use Neos\ContentRepository\Core\NodeType\NodeType;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Package\FlowPackageInterface;

#[Flow\Proxy(false)]
readonly class NodeInterfaceSpecification
{
    public function __construct(
        public NodeInterfaceNameSpecification $interfaceName,
        public NodeInterfaceNameSpecificationCollection $interfaceNames,
        public NodePropertySpecificationCollection $properties,
        public string $directory,
        public string $interfaceFilename,
    ) {
    }

    public static function createFromPackageAndNodeType(
        FlowPackageInterface $package,
        NodeType $nodeType,
    ): self {

        if (!str_starts_with($nodeType->name->value, $package->getPackageKey() . ':')) {
            throw new \Exception("Only nodetypes from the given package are allowed");
        }

        $nameSpecification = NodeInterfaceNameSpecification::createFromNodeType($nodeType);

        $localNameParts = explode('.', str_replace($package->getPackageKey() . ':', '', $nodeType->name->value));
        $localName = array_pop($localNameParts);
        $localNamespace = implode('.', $localNameParts);

        $directory = $package->getPackagePath()
            . 'NodeTypes' . DIRECTORY_SEPARATOR
            . ($localNamespace ? str_replace('.', DIRECTORY_SEPARATOR, $localNamespace) . DIRECTORY_SEPARATOR : '')
            . $localName;

        $interfaceFileName =  $directory . DIRECTORY_SEPARATOR . $nameSpecification->interfaceName . '.php';

        return new self(
            $nameSpecification,
            NodeInterfaceNameSpecificationCollection::createFromNodeType($nodeType),
            NodePropertySpecificationCollection::createFromNodeType($nodeType),
            $directory,
            $interfaceFileName
        );
    }

    public function toPhpString(): ?string
    {

        $propertyAccessors = '';
        $internalPropertyAccessors = '';

        foreach ($this->properties as $property) {
            $propertyIsInternal = str_starts_with($property->propertyName, '_');
            if ($propertyIsInternal) {
                $internalPropertyAccessors .= $property->toPhpInterfaceMethodString();
            } else {
                $propertyAccessors .= $property->toPhpInterfaceMethodString();
            }
        }

        $class = <<<EOL
        <?php

        declare(strict_types=1);

        namespace {$this->interfaceName->phpNamespace};

        use Neos\ContentRepository\Domain\Model\NodeInterface;
        use Neos\Flow\Annotations as Flow;

        /**
         * AUTOGENERATED CODE ... DO NOT MODIFY !!!
         *
         * run `./flow nodetypeobjects:build` to regenerate this
         */
        interface {$this->interfaceName->interfaceName}
        {
            // property accessors
            $propertyAccessors

            // internal property accessors
            $internalPropertyAccessors
        }

        EOL;

        return $class;
    }
}
