<?php

declare(strict_types=1);

namespace PackageFactory\NodeTypeObjects\Domain;

use Neos\ContentRepository\Core\NodeType\NodeType;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Package\FlowPackageInterface;

#[Flow\Proxy(false)]
readonly class NodeInterfaceSpecification
{
    public function __construct(
        public NodeInterfaceNameSpecification $interfaceName,
        public NodePropertySpecificationCollection $properties,
    ) {
    }

    public static function createFromNodeType(
        NodeType $nodeType,
    ): self {
        return new self(
            NodeInterfaceNameSpecification::createFromNodeType($nodeType),
            NodePropertySpecificationCollection::createFromNodeType($nodeType),
        );
    }

    public function toPhpString(): ?string
    {

        $propertyAccessors = '';
        $internalPropertyAccessors = '';

        foreach ($this->properties as $property) {
            $propertyIsInternal = str_starts_with($property->propertyName, '_');
            if ($propertyIsInternal) {
                $internalPropertyAccessors .= $property->toPhpInterfaceMethodString();
            } else {
                $propertyAccessors .= $property->toPhpInterfaceMethodString();
            }
        }

        $class = <<<EOL
        <?php

        declare(strict_types=1);

        namespace {$this->interfaceName->getFullNamespace()};

        use Neos\ContentRepository\Domain\Model\NodeInterface;
        use Neos\Flow\Annotations as Flow;

        /**
         * AUTOGENERATED CODE ... DO NOT MODIFY !!!
         *
         * run `./flow nodebjects:build` to regenerate this
         */
        interface {$this->interfaceName->interfaceName}
        {
            // property accessors
            $propertyAccessors

            // internal property accessors
            $internalPropertyAccessors
        }

        EOL;

        return $class;
    }
}
