<?php

declare(strict_types=1);

namespace PackageFactory\NodeTypeObjects\Domain;

use Neos\ContentRepository\Core\NodeType\NodeType;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Package\FlowPackageInterface;

#[Flow\Proxy(false)]
readonly class NodeObjectSpecification
{
    public function __construct(
        public NodeObjectNameSpecification $objectName,
        public NodeInterfaceNameSpecificationCollection $interfaceNames,
        public NodePropertySpecificationCollection $properties,
    ) {
    }

    public static function createFromNodeType(
        NodeType $nodeType,
    ): self {
        return new self(
            NodeObjectNameSpecification::createFromNodeType($nodeType),
            NodeInterfaceNameSpecificationCollection::createFromNodeType($nodeType, true),
            NodePropertySpecificationCollection::createFromNodeType($nodeType),
        );
    }

    public function toPhpString(): string
    {
        $propertyAccessors = '';
        $internalPropertyAccessors = '';

        foreach ($this->properties as $property) {
            $propertyIsInternal = str_starts_with($property->propertyName, '_');
            if ($propertyIsInternal) {
                $internalPropertyAccessors .= $property->toPhpClassMethodString();
            } else {
                $propertyAccessors .= $property->toPhpClassMethodString();
            }
        }

        $interfaceDeclaration = $this->interfaceNames->asImplementsStatement();

        $class = <<<EOL
        <?php

        declare(strict_types=1);

        namespace {$this->objectName->getFullNamespace()};

        use Neos\ContentRepository\Core\Projection\ContentGraph\Node;
        use Neos\Flow\Annotations as Flow;

        /**
         * AUTOGENERATED CODE ... DO NOT MODIFY !!!
         *
         * run `./flow nodeobjects:build` to regenerate this
         */
        #[Flow\Proxy(false)]
        final readonly class {$this->objectName->className} {$interfaceDeclaration}
        {
            private function __construct(
                public Node \$node
            ) {
            }

            public static function fromNode(Node \$node): self
            {
                if (\$node->nodeTypeName->value !== "{$this->objectName->nodeTypeName}") {
                    throw new \Exception("unsupported nodetype " . \$node->nodeTypeName->value);
                }
                return new self(\$node);
            }

            // property accessors
            {$propertyAccessors}

            // internal property accessors
            {$internalPropertyAccessors}
        }

        EOL;

        return $class;
    }
}
