<?php

declare(strict_types=1);

namespace PackageFactory\NodeTypeObjects\Domain;

use Neos\ContentRepository\Core\NodeType\NodeType;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Package\FlowPackageInterface;

#[Flow\Proxy(false)]
readonly class NodeObjectSpecification
{
    public function __construct(
        public NodeObjectNameSpecification $objectName,
        public NodeInterfaceNameSpecificationCollection $interfaceNames,
        public NodePropertySpecificationCollection $properties,
        public string $directory,
        public string $classFilename,
    ) {
    }

    public static function createFromPackageAndNodeType(
        FlowPackageInterface $package,
        NodeType $nodeType,
    ): self {

        if (!str_starts_with($nodeType->name->value, $package->getPackageKey() . ':')) {
            throw new \Exception("Only nodetypes from the given package are allowed");
        }

        $nameSpecification = NodeObjectNameSpecification::createFromNodeType($nodeType);

        $localNameParts = explode('.', str_replace($package->getPackageKey() . ':', '', $nodeType->name->value));
        $localName = array_pop($localNameParts);
        $localNamespace = implode('.', $localNameParts);

        $directory = $package->getPackagePath()
            . 'NodeTypes' . DIRECTORY_SEPARATOR
            . ($localNamespace ? str_replace('.', DIRECTORY_SEPARATOR, $localNamespace) . DIRECTORY_SEPARATOR : '')
            . $localName;

        $classFilename = $directory . DIRECTORY_SEPARATOR . $nameSpecification->className . '.php';

        return new self(
            $nameSpecification,
            NodeInterfaceNameSpecificationCollection::createFromNodeType($nodeType, true),
            NodePropertySpecificationCollection::createFromNodeType($nodeType),
            $directory,
            $classFilename
        );
    }

    public function toPhpString(): string
    {
        $propertyAccessors = '';
        $internalPropertyAccessors = '';

        foreach ($this->properties as $property) {
            $propertyIsInternal = str_starts_with($property->propertyName, '_');
            if ($propertyIsInternal) {
                $internalPropertyAccessors .= $property->toPhpClassMethodString();
            } else {
                $propertyAccessors .= $property->toPhpClassMethodString();
            }
        }

        $interfaceDeclaration = $this->interfaceNames->asImplementsStatement();

        $class = <<<EOL
        <?php

        declare(strict_types=1);

        namespace {$this->objectName->phpNamespace};

        use Neos\ContentRepository\Core\Projection\ContentGraph\Node;
        use Neos\Flow\Annotations as Flow;

        /**
         * AUTOGENERATED CODE ... DO NOT MODIFY !!!
         *
         * run `./flow nodeobjects:build` to regenerate this
         */
        #[Flow\Proxy(false)]
        final readonly class {$this->objectName->className} {$interfaceDeclaration}
        {
            private function __construct(
                public Node \$node
            ) {
            }

            public static function fromNode(Node \$node): self
            {
                if (\$node->nodeTypeName->value !== "{$this->objectName->nodeTypeName}") {
                    throw new \Exception("unsupported nodetype " . \$node->nodeTypeName->value);
                }
                return new self(\$node);
            }

            // property accessors
            {$propertyAccessors}

            // internal property accessors
            {$internalPropertyAccessors}
        }

        EOL;

        return $class;
    }
}
